config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tab.urls')),
]

urlpatterns += static(settings.IMAGE_ACCESS_URL,
                      document_root=settings.IMAGE_ACCESS_ROOT)

handler404 = 'tab.views.notfound'

tab/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from tab import views

app_name = 'tab'
urlpatterns = [
    path('board/', views.board, name='board'),
    path('board/detail/<int:content_id>',
         views.board_detail, name='board_detail'),
    path('board/post', views.board_post, name='board_post'),
    path('board/modify/<int:content_id>',
         views.board_modify, name='board_modify'),
    path('board/delete/<int:content_id>',
         views.board_delete, name='board_delete'),
    path('recruiting/', views.recruiting, name='recruiting'),
    path('recruiting/success/', views.recruiting_success,
         name='recruiting_success'),
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(template_name='tab/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

tab/models.py
from django.db import models
from django.utils import timezone
from django.core.exceptions import ValidationError


class Post(models.Model):
    subject = models.CharField(max_length=16)
    content = models.TextField()
    main_image = models.ImageField(
        upload_to='postimages', blank=True, null=True)
    create_date = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.subject


class Application(models.Model):
    def _validate_file(value):
        value = str(value)
        if value.endswith('.pdf') or value.endswith('.doc') or value.endswith('.docx') or value.endswith('.txt'):
            return value
        raise ValidationError("지원하지 않는 파일 형식입니다.")

    def _set_file_path(instance, filename):
        file_format = filename.split('.')[-1]
        datetime_str = timezone.datetime.strftime(timezone.now(), '%Y-%m')
        return f'applications/{datetime_str}/{instance.studentnumber}_{instance.name}.{file_format}'

    name = models.CharField(max_length=8)
    studentnumber = models.CharField(max_length=16)
    phonenumber = models.CharField(max_length=11)
    file_path = models.FileField(upload_to=_set_file_path,
                                 validators=[_validate_file])
    create_date = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name = 'Application'
        verbose_name_plural = 'Applications'

    def __str__(self):
        return f'{self.studentnumber}_{self.name}'

forms.py
from django import forms

from tab.models import Post, Application


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['subject', 'content']


class ApplicationForm(forms.ModelForm):
    class Meta:
        model = Application
        fields = ['name', 'studentnumber', 'phonenumber', 'file_path']

tab/views.py
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

from os import listdir
from random import choice

from tab.models import Post
from forms import PostForm, ApplicationForm


def _get_random_image():
    images = [image for image in listdir('./static/assets/img/random')]
    return choice(images)


def index(request):
    return render(request, 'tab/index.html')


def board(request):
    page = request.GET.get('page', '1')
    contents = Post.objects.order_by('-create_date')
    paginator = Paginator(contents, 10)
    context = {'contents': paginator.get_page(page)}
    return render(request, 'tab/board.html', context)


def board_detail(request, content_id):
    content = get_object_or_404(Post, pk=content_id)
    context = {'content': content, 'bg_img': _get_random_image()}
    return render(request, 'tab/board_detail.html', context)


@login_required(login_url='tab:login')
def board_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('tab:board')
    else:
        form = PostForm()
    context = {'form': form, 'bg_img': _get_random_image()}
    return render(request, 'tab/board_post.html', context)


@login_required(login_url='tab:login')
def board_modify(request, content_id):
    content = get_object_or_404(Post, pk=content_id)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=content)
        if form.is_valid():
            content = form.save()
            return redirect('tab:board_detail', content_id)
    else:
        form = PostForm(instance=content)
    context = {'form': form, 'content': content, 'bg_img': _get_random_image()}
    return render(request, 'tab/board_post.html', context)


@login_required(login_url='tab:login')
def board_delete(request, content_id):
    content = get_object_or_404(Post, pk=content_id)
    content.delete()
    return redirect('tab:board')


def recruiting(request):
    if request.method == 'POST':
        form = ApplicationForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('tab:recruiting_success')
    else:
        form = ApplicationForm()
    context = {'form': form}
    return render(request, 'tab/recruiting.html', context)


def recruiting_success(request):
    return render(request, 'tab/recruiting_success.html')


def notfound(request, exception):
    return render(request, 'notfound.html')

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="icon" type="image/x-icon" href="{% static 'assets/img/tab_icon.jfif' %}" />
    <title>TAB</title>

    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
    
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
  </head>
  <body>
    {% include "navbar.html" %}
    
    {% block content %}
    {% endblock %}

    {% include "footer.html" %}

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
    {% block script %}
    {% endblock %}
  </body>
</html>

templates/board_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Page Header-->
<header class="masthead" style="background-image: url({% static 'assets/img/post-bg.jpg' %})">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="post-heading">
          <h1>{{ content.subject }}</h1>
          <span class="meta">
            {{ content.create_date|date:"Y m d"}}
          </span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Post Content-->
<article class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p class="text-break">{{ content.content }}</p>
      </div>
    </div>
    {% if user.is_authenticated %}
    <a type="button" class="btn btn-link btn-sm" href="{% url 'tab:board_modify' content.id %}">수정</a>
    <a type="button" class="btn btn-link btn-sm" href="{% url 'tab:board_delete' content.id %}">삭제</a>
    {% endif %}
  </div>
</article>
{% endblock %}

templates/footer.html
<!-- Footer-->
<footer class="border-top">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <!-- <ul class="list-inline text-center">
          <li class="list-inline-item">
            <a href="#!">
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#!">
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="#!">
              <span class="fa-stack fa-lg">
                <i class="fas fa-circle fa-stack-2x"></i>
                <i class="fab fa-github fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
        </ul> -->
        <div class="small text-center text-muted fst-italic">Copyright &copy; HUFS TAB 2022</div>
      </div>
    </div>
  </div>
</footer>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/header.html
{% load static %}
<header class="masthead" style="background-image: url({% static 'assets/img/'|add:bg_img %})">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>{{ title }}</h1>
          <span class="subheading">{{ subtitle }}</span>
        </div>
      </div>
    </div>
  </div>
</header>

templates/header_post.html
<header class="masthead" style="background-image: url('static/{{ bg_img }}')">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="post-heading">
          <h1>{{ title }}</h1>
          <span class="meta">{{ subtitle }}</span>
        </div>
      </div>
    </div>
  </div>
</header>

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Page Header-->
<header class="masthead" style="background-image: url({% static 'assets/img/home-bg.jpg' %})">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>TAB 로그인</h1>
          <span class="subheading">한 줄 소개</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main -->
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="my-5">
          <form id="contactForm" method="post">
            {% csrf_token %}
            <div class="form-floating">
              <input class="form-control" id="username" type="text" placeholder="ID" name="username" />
              <label for="username">ID</label>
            </div>
            <div class="form-floating">
              <input class="form-control" id="password" type="password" placeholder="PW" name="password" />
              <label for="password">PW</label>
            </div>
            <br />
            <!-- Submit Button-->
            <button type="submit" class="btn btn-primary">로그인</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

templates/navbar.html
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
  <div class="container px-4 px-lg-5">
    <a class="navbar-brand" href="{% url 'tab:index' %}">TAB</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto py-4 py-lg-0">
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'tab:index' %}">소개</a></li>
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'tab:board' %}">게시판</a></li>
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'tab:recruiting' %}">지원하기</a></li>
        {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'tab:logout' %}">로그아웃</a></li>
        {% else %}
        <li class="nav-item"><a class="nav-link px-lg-3 py-3 py-lg-4" href="{% url 'tab:login' %}">로그인</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

templates/notfound.html
{% extends 'base.html' %}
{% block content %}
<!-- Page Header-->
{% include 'header.html' with bg_img='notfound.jpg' title='404' subtitle='Not Found' %}
{% endblock %}

templates/recruiting.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Page Header-->
<header class="masthead" style="background-image: url({% static 'assets/img/contact-bg.jpg' %})">
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>TAB 지원</h1>
          <span class="subheading">한 줄 소개</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <h5>지원서 양식</h5>
        <p>
          <ul>
            <li>TAB은 자유양식의 지원서를 받고 있습니다. 지원동기, 프로그래밍 경험, 관심 분야 등 본인을 자유롭게 표현해주세요.</li>
            <li>파일명은 '학번_이름'으로 제출해주세요.</li>
            <li>PDF, Word, txt 파일로 제출해주세요.</li>
          </ul>
        </p>
        <h5>자주하는 질문</h5>
        <p>
          <ul>
            <li>TAB은 합/불 결과에 관계없이 기입한 전화번호로 결과를 알려드립니다.</li>
            <li>가입 절차는 '서류지원 -> 화상면접 -> 최종합격'의 순서입니다.</li>
          </ul>
        </p>
        <div class="my-5">
          <form id="contactForm" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-floating">
              <input class="form-control" id="name" type="text" placeholder="이름" maxlength="8" name="name" />
              <label for="name">이름</label>
            </div>
            <div class="form-floating">
              <input class="form-control" id="studentnumber" type="text" placeholder="학번" maxlength="16" name="studentnumber" />
              <label for="studentnumber">학번</label>
            </div>
            <div class="form-floating">
              <input class="form-control" id="phonenumber" type="tel" placeholder="전화번호" pattern="[0-9]{11}" name="phonenumber" />
              <label for="phonenumber">전화번호</label>
            </div>
            <div class="mt-3">
              <label for="application" class="form-label">지원서 첨부 (최대 2.5MB)</label>
              <input class="form-control" type="file" id="application" name="path" accept=".pdf,.doc,.docx,.txt">
            </div>
            <br />
            <!-- Submit Button-->
            <button type="submit" class="btn btn-primary">지원하기</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

templates/recruiting_success.html
{% extends 'base.html' %}
{% block content %}
<div class="card my-3">
  <div class="card-header text-center">
    <h2>{{ name }}님, TAB에 지원해 주셔서 감사합니다:)</h2>
  </div>
  <div class="card-body">
    <h5 class="card-title">제출 결과</h5>
    <p class="card-text">
      <ul>
        <li>성공적으로 제출되었습니다. TAB 학회원 분들이 서류를 검토중입니다.</li>
        <li>합/불 결과에 관계없이 <strong>{{ phonenumber }}</strong>로 연락드리겠습니다.</li>
      </ul>
    </p>
    <h5 class="card-title">참고해주세요.</h5>
    <p class="card-text">
      <ul>
        <li>가입 절차는 '서류지원 -> 화상면접 -> 최종합격'의 순서입니다.</li>
        <li>이외 궁금한 점은 example@domain.com으로 문의 바랍니다.</li>
      </ul>
    </p>
  </div>
  <div class="card-footer text-muted">
    감사합니다.
  </div>
</div>
{% endblock %}

templates/tab/board.html
{% extends 'base.html' %}
{% block content %}
<!-- Page Header-->
{% include 'header.html' with bg_img='board_bg.jpg' title='게시판' subtitle='Just Do It!' %}
<!-- Main Content-->
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      {% for content in contents %}
      <!-- Post preview-->
      <div class="post-preview">
        <a href="{% url 'tab:board_detail' content.id %}">
          <h2 class="post-title">{{ content.subject }}</h2>
        </a>
        <p class="post-meta">
          {{ content.create_date|date:"Y m d" }}
        </p>
      </div>
      <!-- Divider-->
      <hr class="my-4" />
      {% endfor %}
      <!-- Pager-->
      <div class="d-flex justify-content-end gap-2 mb-4">
        {% if contents.has_previous %}
        <a class="btn btn-primary" href="?page={{ contents.previous_page_number }}">이전</a>
        {% endif %}
        {% if contents.has_next %}
        <a class="btn btn-primary" href="?page={{ contents.next_page_number }}">다음</a>
        {% endif %}
      </div>
      <!-- Write -->
      {% if user.is_authenticated %}
      <div class="d-flex justify-content-end mb-4"><a type="button" class="btn btn-primary" href="{% url 'tab:board_post' %}">글쓰기</a></div>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

templates/tab/board_detail.html
{% extends 'base.html' %}
{% load tab_filter %}
{% block content %}
<!-- Page Header-->
{% include 'header.html' with bg_img='random/'|add:bg_img  title=content.subject subtitle=content.create_date|date:'Y m d' %}
<!-- Main Content-->
<article class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7 text-break">
        {% if content.main_image %}
        <img class="img-fluid my-5" src="{{ content.main_image.url }}" />
        {% endif %}
        {{ content.content|mark }}
      </div>
    </div>
    {% if user.is_authenticated %}
    {{ image }}
    <a type="button" class="btn btn-link btn-sm" href="{% url 'tab:board_modify' content.id %}">수정</a>
    <a type="button" class="btn btn-link btn-sm" href="{% url 'tab:board_delete' content.id %}">삭제</a>
    {% endif %}
  </div>
</article>
{% endblock %}

templates/tab/board_post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% include "header.html" with bg_img='random/'|add:bg_img title="TAB 글쓰기" subtitle="게시글 작성" %}
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="my-5">
          <form method="post">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="form-floating">
              <input class="form-control" id="subject" type="text" placeholder="제목" maxlength="16" value="{{ form.subject.value|default_if_none:'' }}" name="subject" />
              <label for="subject">제목</label>
            </div>
            <div class="form-floating">
              <textarea style="height: 50%;" class="form-control" id="content" placeholder="내용" name="content" rows="20">{{ form.content.value|default_if_none:'' }}</textarea>
              <label for="content">내용</label>
            </div>
            <div class="mt-3">
              <label for="mainImage" class="form-label">이미지 첨부</label>
              <input class="form-control" type="file" accept="image/*" id="mainImage" name="main_image" />
            </div>
            <br />
            <!-- Submit Button-->
            <button type="submit" class="btn btn-primary">작성하기</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

templates/tab/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Page Header-->
{% include 'header.html' with bg_img='index_bg.jpg' title='TAB' subtitle='Talk About Bug' %}
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>
          TAB은 키보드의 Tab키와 'Talk About Bug'의 약자로 '프로그래밍 개발 지식 공유'라는 의미를 두고 있는 1982년에 설립된 컴퓨터공학부 소속 학회입니다. 함께 프로그래밍 지식에 대한 대화를 나누고, 자신이 관심있는 분야를 함께 공부하며 전공 수업 이외의 부분들을 함께 공유하여 학회원들의 실력 향상을 도모하고 있습니다. 저희는 보다 한 분야에 국한되지 않아 다양한 공부를 접할 수 있는 기회를 제공합니다. 또한, 선후배간의 친목을 도모하고, 재학생들 뿐만 아니라 졸업생들과의 네트워킹할 수 있는 다양한 활동들을 진행하고 있습니다.
        </p>
        <h3>스터디</h3>
        <hr />
        <img class="img-fluid" src="{% static 'assets/img/study.jpg' %}" />
        <p>학회원들끼리 관심있는 주제로 서로 팀을 이뤄 공부하거나 세미나를 직접 진행합니다.<br />
        웹, 앱(안드로이드, iOS), 게임, 머신러닝, 보안, 알고리즘 등</p>
        <h3>발표</h3>
        <hr />
        <img class="img-fluid" src="{% static 'assets/img/presentation.jpg' %}" />
        <p>개인 혹은 팀으로 진행한 프로젝트, 개인이 공부한 주제를 갖고 학기 중에 발표할 수 있는 기회를 갖습니다.</p>
        <h3>야유회</h3>
        <hr />
        <img class="img-fluid" src="{% static 'assets/img/picnic.jpg' %}" />
        <p>봄에 서울 올림픽 공원에서 졸업한 학회 선배님들과 네트워킹할 수 있는 야유회를 진행합니다.</p>
        <h3>캠핑 및 MT</h3>
        <hr />
        <img class="img-fluid" src="{% static 'assets/img/retreat.jpg' %}" />
        <p>여름과 가을 사이 MT를 진행하여 학회원들간에 친목도모 할 수 있는 시간을 갖습니다.</p>
      </div>
    </div>
  </div>
</main>
{% endblock %}

templates/tab/login.html
{% extends 'base.html' %}
{% block content %}
<!-- Page Header-->
{% include 'header.html' with bg_img='login_bg.jpg' title='로그인' subtitle='' %}
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="my-5">
          <form method="post">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="form-floating">
              <input class="form-control" id="username" type="text" placeholder="ID" name="username" value="{{ form.username.value|default_if_none:'' }}" />
              <label for="username">ID</label>
            </div>
            <div class="form-floating">
              <input class="form-control" id="password" type="password" placeholder="PW" name="password" />
              <label for="password">PW</label>
            </div>
            <br />
            <!-- Submit Button-->
            <button type="submit" class="btn btn-primary">로그인</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

templates/tab/recruiting.html
{% extends 'base.html' %}
{% block content %}
<!-- Page Header-->
{% include 'header.html' with bg_img='recruiting_bg.jpg' title='지원하기' subtitle='Better Alone, Best Together' %}
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <h5>지원서 양식</h5>
        <p>
          <ul>
            <li>TAB은 자유양식의 지원서를 받고 있습니다. 지원동기, 프로그래밍 경험, 관심 분야 등 본인을 자유롭게 표현해주세요.</li>
            <li>파일명은 자유롭게 제출해 주세요. 자동으로 입력하신 학번과 이름으로 저장됩니다.</li>
            <li>.pdf, .doc, .docx, .txt 파일로 제출해주세요.</li>
          </ul>
        </p>
        <h5>자주하는 질문</h5>
        <p>
          <ul>
            <li>TAB은 합/불 결과에 관계없이 기입한 전화번호로 결과를 알려드립니다.</li>
            <li>가입 절차는 '서류지원 -> 화상면접 -> 최종합격'의 순서입니다.</li>
          </ul>
        </p>
        <div class="my-5">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {% include "form_errors.html" %}
            <div class="form-floating">
              <input class="form-control" id="name" type="text" placeholder="이름" maxlength="8" name="name" value="{{ form.name.value|default_if_none:'' }}" />
              <label for="name">이름</label>
            </div>
            <div class="form-floating">
              <input class="form-control" id="studentnumber" type="text" placeholder="학번" maxlength="16" name="studentnumber" value="{{ form.studentnumber.value|default_if_none:'' }}" />
              <label for="studentnumber">학번</label>
            </div>
            <div class="form-floating">
              <input class="form-control" id="phonenumber" type="tel" placeholder="전화번호" pattern="[0-9]{11}" name="phonenumber" value="{{ form.phonenumber.value|default_if_none:'' }}" />
              <label for="phonenumber">전화번호</label>
            </div>
            <div class="mt-3">
              <label for="application" class="form-label">지원서 첨부 (최대 2.5MB)</label>
              <input class="form-control" type="file" id="application" name="file_path" accept=".pdf,.doc,.docx,.txt" />
            </div>
            <br />
            <!-- Submit Button-->
            <div class="d-flex justify-content-end">
              <button type="submit" class="btn btn-primary">지원하기</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

templates/tab/recruiting_success.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Page Header-->
{% include 'header.html' with bg_img='recruiting_bg.jpg' title='지원완료' subtitle='TAB에 지원해 주셔서 감사합니다:)' %}
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <h5>제출 결과</h5>
        <p>
          <ul>
            <li>성공적으로 제출되었습니다. TAB 학회원 분들이 서류를 확인중입니다.</li>
            <li>합/불 결과에 관계없이 기입한 전화번호로 결과를 알려드립니다.</li>
          </ul>
        </p>
      </div>
    </div>
  </div>
</main>
{% endblock %}